REQUIRE PLACE  ~mak\place.f 
REQUIRE [IF] ~MAK\CompIF3.f
[IFNDEF] BREAK : BREAK  POSTPONE EXIT POSTPONE THEN ; IMMEDIATE  [THEN]

C" STREAM-FILE" FIND NIP
[IF]
: FROM_SOURCE-ID SOURCE-ID  STREAM-FILE ;
: TO_SOURCE-ID FILE>RSTREAM TO SOURCE-ID ;
[ELSE]
: FROM_SOURCE-ID SOURCE-ID ;
: TO_SOURCE-ID TO SOURCE-ID ;
[THEN]

C" -CELL" FIND NIP 0=
[IF] -1 CELLS CONSTANT -CELL
[THEN]

[IFNDEF] HERE-TAB-CUR VARIABLE HERE-TAB-CUR
[THEN]

MODULE: AVRLIST

CREATE  FILE_NAME_L 120 ALLOT

CREATE   HERE-TAB  4000 CELLS ALLOT
HERE CELL-  CONSTANT HERE-TAB-MAX
HERE-TAB HERE-TAB-CUR !
VARIABLE S_STATE 

: HERE-TAB-CUR+
  HERE-TAB-CUR @  CELL+ HERE-TAB-MAX UMIN
  HERE-TAB-CUR
 !
\ [ .( XXXX) DIS-OPT KEY DROP ]
 ;

0 VALUE CURFILEHTC

: HERE-TO-TAB
\+ CURFILE CURFILEHTC 0= IF CURFILE @ TO CURFILEHTC THEN
\+ CURFILE CURFILE @ CURFILEHTC <> IF BREAK
 DP @ HERE-TAB-CUR @ !
 HERE-TAB-CUR+
 DP @ HERE-TAB-CUR @ !
 ;

80 VALUE DUMP_MAX 


: .LIST ( ADDR  ADDR1 -- ADDR1' ) 
\          CR H. EXIT
          S_STATE @ DROP 1
          IF
             SWAP
             BEGIN  2DUP U> 
             WHILE  MINST CR
             REPEAT  NIP
          ELSE
            TUCK   
            OVER - DUP
            IF   DUP DUMP_MAX U>

                IF  >R DUMP_MAX DUMP 
                    CR DUP U.  R> DUMP_MAX - U. ." bytes"
                ELSE  DUMP
                THEN CR
            ELSE 2DROP
            THEN
          THEN
;

VECT INCLUDED$

' INCLUDED TO INCLUDED$

EXPORT

: CON_EMIT
   H-STDOUT >R  [ H-STDOUT LIT, ] TO H-STDOUT EMIT
   R> TO H-STDOUT ;

: STCR_
     SOURCE TYPE CR
 ; 

VECT STCR
' STCR_ TO STCR

HERE S" _AL" S", VALUE C"_AL"

0 VALUE INCL-HH

0 VALUE TMPH-STDOUT
\- C/L $101 CONSTANT C/L
CREATE LS_TIB C/L ALLOT

: INCLUDED_AL

 HERE TO INCL-HH
   ['] <PRE> >BODY @ >R
   ['] HERE-TO-TAB TO <PRE>
	0 TO CURFILEHTC
     HERE-TAB  HERE-TAB-CUR !
  2DUP 2>R
  INCLUDED$ 
 2R>  R> TO <PRE>
    HERE-TO-TAB
    HERE-TO-TAB		-CELL HERE-TAB-CUR +!
    HERE-TAB-CUR @ @	-CELL HERE-TAB-CUR +!
    BEGIN HERE-TAB-CUR @ HERE-TAB <>
    WHILE HERE-TAB-CUR @ @ UMIN DUP HERE-TAB-CUR @ !
          -CELL HERE-TAB-CUR +!
    REPEAT DROP
    S_STATE 0!

    2DUP FILE_NAME_L  PLACE
  C"_AL" COUNT FILE_NAME_L +PLACE  
  R/O OPEN-FILE-SHARED  THROW
  FILE_NAME_L COUNT 2DUP + 0!

  W/O CREATE-FILE-SHARED THROW

 #TIB @ >R  TIB >R >IN @ >R
 SOURCE-ID >R CURSTR @ >R
  H-STDOUT >R  BASE @ >R HEX
  TO H-STDOUT
\     F7_ED
\  C/L  2 + ALLOCATE THROW TO TIB
 LS_TIB TO TIB
\+ NOTIV? -1 TO NOTIV?
  TO_SOURCE-ID
  CURSTR 0! HERE-TAB-CUR @ @
  BEGIN    REFILL
  WHILE \ [CHAR] * CON_EMIT
        STCR
	HERE-TAB-CUR+ HERE-TAB-CUR @ @   .LIST
  REPEAT  DROP
\  TIB FREE THROW
  FROM_SOURCE-ID  CLOSE-FILE THROW
   H-STDOUT CLOSE-FILE THROW
  R> BASE ! R> TO H-STDOUT
  R> CURSTR ! R> TO SOURCE-ID R> >IN !
 R> TO TIB  R> #TIB !
 CR FILE_NAME_L COUNT TYPE 9 EMIT HERE INCL-HH - .

;

: REQUIRED_AL ( waddr wu laddr lu -- )
  2SWAP SFIND
  IF DROP 2DROP EXIT
  ELSE 2DROP INCLUDED_AL THEN
;
: REQUIRE_AL ( "word" "libpath" -- )
  BL PSKIP BL PARSE
  BL PSKIP BL PARSE 2DUP + 0 SWAP C!
  REQUIRED_AL
;

;MODULE

\EOF
: : : SHERE-TO-TAB ;

: ; POSTPONE ; SHERE-TO-TAB ; IMMEDIATE

: SSSS
     HERE-TAB  HERE-TAB-CUR !
    SHERE-TAB SHERE-TAB-CUR ! 
;
