
REQUIRE $! ~mak\place.f

\- DALLOT : DALLOT ALLOT ;

$1000 CONSTANT TP_STACK_SIZE
TP_STACK_SIZE $10 + ALLOCATE THROW CONSTANT TP_STACK_BOTTOM
TP_STACK_BOTTOM TP_STACK_SIZE +  VALUE TP_ST_P

: >TP_ST TP_ST_P CELL- TO TP_ST_P TP_ST_P ! ;
: TP_ST@ TP_ST_P @ ;
: TP_ST> TP_ST@ TP_ST_P CELL+ TO TP_ST_P ;

: #BEGIN
 CR ." [BEGIN]" SOURCE TYPE
 >IN @ >TP_ST
  DP @ >TP_ST
  CURSTR @ >TP_ST  
  SOURCE-ID FILE-POSITION DROP >TP_ST >TP_ST

\  SOURCE XSOURCE $!
  
  TP_ST_P
  $101 -
  TO TP_ST_P
  SOURCE TP_ST_P $!
;

: #AGAIN
 CR ." [AGAIN]" SOURCE TYPE
   TP_ST_P COUNT DUP #TIB ! TIB SWAP MOVE
    TP_ST_P
    $101 +
    TO TP_ST_P	

\   XSOURCE COUNT DUP #TIB ! TIB SWAP MOVE
		
   TP_ST> TP_ST> SOURCE-ID REPOSITION-FILE DROP   
   TP_ST>  CURSTR  !
   TP_ST>  DP  !
   TP_ST>  >IN  !
  #BEGIN
;

: #TP_REST
    TP_ST_P
    $101 +
    5 CELLS +
    TO TP_ST_P	
  
;

: #UNTIL 
 f7_ed 
  IF 
  #TP_REST 
  BREAK 
  #AGAIN
  ;
